---
title: "CFS Analysis"
author: "Hari Dave"
date: "06/09/2025"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Year 2012 

\textbf{Code} 
```{r}

library(MASS)

save_folder = '.\\Analysis_2012\\'


read_data <- read.csv(paste(save_folder,'instrument_training.csv',
                            sep=""))

d <- data.frame(as.list(1:nrow(read_data)))
idx_d <- which(d%%2==1)
idx_no_self <- which(read_data[, 1]!=read_data[, 2])

subset_data<- read_data[intersect(idx_d, idx_no_self), ]

self_just_once <- intersect(which(d%%2==1), which(read_data[, 1]==read_data[, 2]))
subset_data_2 <- read_data[self_just_once,]

subset_data_3 <- rbind(subset_data, subset_data_2)
idx_not_CONUS <- which(subset_data_3[,1]==2 | subset_data_3[,1]==15 |
                         subset_data_3[,2]==2 | subset_data_3[,2]==15)
subset_data_3<-subset_data_3[-idx_not_CONUS, ]

column_names<- c('Exporter', 'Importer', 'Shipments', 'Distance', 
                 'Area_exporter', 'Area_importer', 
                 'Population_exporter', 'Population_importer', 
                 'GDP_exporter', 'GDP_importer', 
                 'Intrastate_or_not', 'Share_Border', 
                 'BorderxArea_exporter', 'BorderxArea_importer',
                 'BorderxPop_exporter', 'BorderxPop_importer', 
                 'BorderxDist', 'sum_LL',
                 'Borderxsum_LL', 'Long_ex', 'Lat_ex', 'Long_im', 
                 'Lat_im', 'Is_DC_involved', 'LL_ex', 'LL_im',
                 'num_FAF_ex', 'num_FAF_im', 'remoteness_ex', 'remoteness_im')



take_log_columns = c('Shipments', 'Distance', 
                     'Area_exporter', 'Area_importer', 
                     'Population_exporter', 'Population_importer', 
                     'GDP_exporter', 'GDP_importer',
                     'remoteness_ex', 'remoteness_im')

subset_data_3[,take_log_columns] <- log(subset_data_3[,take_log_columns])

subset_data_3$Interstate_or_not <- 1-subset_data_3$Intrastate_or_not

subset_data_3$num_FAF_involved <- subset_data_3$num_FAF_ex+subset_data_3$num_FAF_im


row.names(subset_data_3) <- NULL

subset_data_3$Is_importer_north_rel <- pmax(0,sign(subset_data_3$Lat_im-subset_data_3$Lat_ex))
subset_data_3$Is_importer_east_rel <- pmax(0,sign(subset_data_3$Long_im-subset_data_3$Long_ex))

subset_data_3$Share_Border[which(subset_data_3$Exporter==subset_data_3$Importer)]<-1

subset_data_3$inter_B <- subset_data_3$Share_Border*subset_data_3$Interstate_or_not
subset_data_3$inter_D <- subset_data_3$Distance*subset_data_3$Interstate_or_not

subset_data_3$inter_sum_LL <-subset_data_3$Interstate_or_not*subset_data_3$sum_LL
subset_data_3$inter_num_FAF_involved <-subset_data_3$Interstate_or_not*subset_data_3$num_FAF_involved

subset_data_3$inter_A_im <-subset_data_3$Interstate_or_not*subset_data_3$Area_importer
subset_data_3$inter_P_im <-subset_data_3$Interstate_or_not*subset_data_3$Population_importer

subset_data_3$inter_is_im_n <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_north_rel
subset_data_3$inter_is_im_e <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_east_rel

lm_instrument <- glmmPQL(Shipments~
                           Interstate_or_not+
                           inter_D+
                           Area_importer+
                           Population_importer+
                           sum_LL+
                           num_FAF_involved+
                           inter_is_im_n+inter_is_im_e+
                           inter_A_im+inter_P_im+
                           inter_sum_LL+inter_num_FAF_involved+
                           inter_B
                        ,data = subset_data_3, family = gaussian, random=~ 1 | SCTG)


lm_instrument$fitted.values <- predict(lm_instrument,data = subset_data_3)

summary(lm_instrument)

plot(subset_data_3$Shipments, lm_instrument$fitted.values,
     xlab="Real Shipments", ylab="Predicted Shipments")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_shipments.jpg"));
dev.off ();

read_data_1 <- read.csv(paste(save_folder,'IV_training.csv',
                              sep=""))

idx_interstate <- which(subset_data_3[,1]!=subset_data_3[,2])

for(i in 1:nrow(read_data_1)){
  idx_state<-union(which(subset_data_3[,1]==read_data_1[i,1]),
                 which(subset_data_3[,2]==read_data_1[i,1]))
  
  idx_num <- intersect(idx_state, idx_interstate)
  
  idx_den <- which(subset_data_3[,1]==read_data_1[i, 1])
  
  real_num <- sum(exp(subset_data_3$Shipments[idx_num]), na.rm=TRUE)
  temp_num <- sum(floor(exp(lm_instrument$fitted.values[idx_num])), na.rm=TRUE)
  
  real_den <- sum(exp(subset_data_3$Shipments[idx_den]), na.rm=TRUE)
  temp_den <- sum(floor(exp(lm_instrument$fitted.values[idx_den])), na.rm=TRUE)
  
  read_data_1$Real_Openness[i] <- real_num/real_den
  read_data_1$Constructed_Openness[i] <- temp_num/real_den
}

plot(read_data_1$Real_Openness, read_data_1$Constructed_Openness,
     xlab="Real Trade Openness", ylab = "Constructed Trade Openness")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_trade.jpg"));
dev.off ();

read_data_1_next_yr <- read.csv(paste(save_folder,'IV_training_next_yr.csv',
                              sep=""))

read_data_1 <- merge(read_data_1, read_data_1_next_yr, by='State')

water_use_file <- read.csv(paste(save_folder,'water_data_states.csv',
                                 sep=""))
col_names <- c('same_yr_Irrigated_area',	'next_yr_Irrigated_area',
               'next_yr_Irrigated_area_gw', 'next_yr_Irrigated_area_sw',	
               'next_yr_Irrigated_water',	'next_yr_Irrigated_water_gw',	
               'next_yr_Irrigated_water_sw',	'next_yr_irrigated_area_gravity',
              'next_yr_irrigated_area_sprinkler',	'next_yr_irrigated_area_drip')

water_use_file$next_yr_gravity_percent <- water_use_file$next_yr_irrigated_area_gravity/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_sprinkler_percent <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_drip_percent <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_Irrigated_area

water_use_file$next_yr_sprinkler_rel <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_irrigated_area_gravity
water_use_file$next_yr_drip_rel <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_irrigated_area_gravity


read_data_1 <- merge(read_data_1, water_use_file, by='State')

read_data_1[,col_names] = log(read_data_1[, col_names])

write.csv(read_data_1, paste0(save_folder, 'R_openness.csv'))

column_names <- c('State', 'Real_Openness', 'Water_Use', 
                  'Constructed_Openness', 'Income',
                'Precipitation', 'Temperature', 'Population', 
                'Area', 'Latitude', 'Longitude', 'Income2', 'Is.DC')

column_names <- c(column_names, col_names)

lm_stage_1_1 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude, 
                 data = read_data_1)
summary(lm_stage_1_1)
nobs(lm_stage_1_1)

lm_stage_1_2 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_2)
nobs(lm_stage_1_2)

lm_stage_1_3 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_3)
nobs(lm_stage_1_3)

lm_stage_1_4 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_4)
nobs(lm_stage_1_4)

lm_stage_1_5 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent, 
                 data = read_data_1)
summary(lm_stage_1_5)
nobs(lm_stage_1_5)

####################
#################


lm_stage_2_1 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#### real to


lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#################

################# GW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

################## SW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


######################




lm_stage_2_1 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)


#### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################

```


2. Year 2017

\textbf{Code} 
```{r}

library(MASS)

save_folder = '.\\Analysis_2017\\'


read_data <- read.csv(paste(save_folder,'instrument_training.csv',
                            sep=""))

d <- data.frame(as.list(1:nrow(read_data)))
idx_d <- which(d%%2==1)
idx_no_self <- which(read_data[, 1]!=read_data[, 2])

subset_data<- read_data[intersect(idx_d, idx_no_self), ]

self_just_once <- intersect(which(d%%2==1), which(read_data[, 1]==read_data[, 2]))
subset_data_2 <- read_data[self_just_once,]

subset_data_3 <- rbind(subset_data, subset_data_2)
idx_not_CONUS <- which(subset_data_3[,1]==2 | subset_data_3[,1]==15 |
                         subset_data_3[,2]==2 | subset_data_3[,2]==15)
subset_data_3<-subset_data_3[-idx_not_CONUS, ]

column_names<- c('Exporter', 'Importer', 'Shipments', 'Distance', 
                 'Area_exporter', 'Area_importer', 
                 'Population_exporter', 'Population_importer', 
                 'GDP_exporter', 'GDP_importer', 
                 'Intrastate_or_not', 'Share_Border', 
                 'BorderxArea_exporter', 'BorderxArea_importer',
                 'BorderxPop_exporter', 'BorderxPop_importer', 
                 'BorderxDist', 'sum_LL',
                 'Borderxsum_LL', 'Long_ex', 'Lat_ex', 'Long_im', 
                 'Lat_im', 'Is_DC_involved', 'LL_ex', 'LL_im',
                 'num_FAF_ex', 'num_FAF_im', 'remoteness_ex', 'remoteness_im')



take_log_columns = c('Shipments', 'Distance', 
                     'Area_exporter', 'Area_importer', 
                     'Population_exporter', 'Population_importer', 
                     'GDP_exporter', 'GDP_importer',
                     'remoteness_ex', 'remoteness_im')

subset_data_3[,take_log_columns] <- log(subset_data_3[,take_log_columns])

subset_data_3$Interstate_or_not <- 1-subset_data_3$Intrastate_or_not

subset_data_3$num_FAF_involved <- subset_data_3$num_FAF_ex+subset_data_3$num_FAF_im


row.names(subset_data_3) <- NULL

subset_data_3$Is_importer_north_rel <- pmax(0,sign(subset_data_3$Lat_im-subset_data_3$Lat_ex))
subset_data_3$Is_importer_east_rel <- pmax(0,sign(subset_data_3$Long_im-subset_data_3$Long_ex))

subset_data_3$Share_Border[which(subset_data_3$Exporter==subset_data_3$Importer)]<-1

subset_data_3$inter_B <- subset_data_3$Share_Border*subset_data_3$Interstate_or_not
subset_data_3$inter_D <- subset_data_3$Distance*subset_data_3$Interstate_or_not

subset_data_3$inter_sum_LL <-subset_data_3$Interstate_or_not*subset_data_3$sum_LL
subset_data_3$inter_num_FAF_involved <-subset_data_3$Interstate_or_not*subset_data_3$num_FAF_involved

subset_data_3$inter_A_im <-subset_data_3$Interstate_or_not*subset_data_3$Area_importer
subset_data_3$inter_P_im <-subset_data_3$Interstate_or_not*subset_data_3$Population_importer

subset_data_3$inter_is_im_n <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_north_rel
subset_data_3$inter_is_im_e <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_east_rel

lm_instrument <- glmmPQL(Shipments~
                           Interstate_or_not+
                           inter_D+
                           Area_importer+
                           Population_importer+
                           sum_LL+
                           num_FAF_involved+
                           inter_is_im_n+inter_is_im_e+
                           inter_A_im+inter_P_im+
                           inter_sum_LL+inter_num_FAF_involved+
                           inter_B
                        ,data = subset_data_3, family = gaussian, random=~ 1 | SCTG)

lm_instrument$fitted.values <- predict(lm_instrument,data = subset_data_3)

# lm_instrument$fitted.values <- predict(lm_instrument,data = subset_data_3)

summary(lm_instrument)

plot(subset_data_3$Shipments, lm_instrument$fitted.values,
     xlab="Real Shipments", ylab="Predicted Shipments")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_shipments.jpg"));
dev.off ();

read_data_1 <- read.csv(paste(save_folder,'IV_training.csv',
                              sep=""))

idx_interstate <- which(subset_data_3[,1]!=subset_data_3[,2])

for(i in 1:nrow(read_data_1)){
  idx_state<-union(which(subset_data_3[,1]==read_data_1[i,1]),
                 which(subset_data_3[,2]==read_data_1[i,1]))
  
  idx_num <- intersect(idx_state, idx_interstate)
  
  idx_den <- which(subset_data_3[,1]==read_data_1[i, 1])
  
  real_num <- sum(exp(subset_data_3$Shipments[idx_num]), na.rm=TRUE)
  temp_num <- sum(floor(exp(lm_instrument$fitted.values[idx_num])), na.rm=TRUE)
  
  real_den <- sum(exp(subset_data_3$Shipments[idx_den]), na.rm=TRUE)
  temp_den <- sum(floor(exp(lm_instrument$fitted.values[idx_den])), na.rm=TRUE)
  
  read_data_1$Real_Openness[i] <- real_num/real_den
  read_data_1$Constructed_Openness[i] <- temp_num/real_den
}

plot(read_data_1$Real_Openness, read_data_1$Constructed_Openness,
     xlab="Real Trade Openness", ylab = "Constructed Trade Openness")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_trade.jpg"));
dev.off ();

read_data_1_next_yr <- read.csv(paste(save_folder,'IV_training_next_yr.csv',
                              sep=""))

read_data_1 <- merge(read_data_1, read_data_1_next_yr, by='State')

water_use_file <- read.csv(paste(save_folder,'water_data_states.csv',
                                 sep=""))
col_names <- c('same_yr_Irrigated_area',	'next_yr_Irrigated_area',
               'next_yr_Irrigated_area_gw', 'next_yr_Irrigated_area_sw',
               'next_yr_Irrigated_water',	'next_yr_Irrigated_water_gw',	
               'next_yr_Irrigated_water_sw',	'next_yr_irrigated_area_gravity',
              'next_yr_irrigated_area_sprinkler',	'next_yr_irrigated_area_drip')

water_use_file$next_yr_gravity_percent <- water_use_file$next_yr_irrigated_area_gravity/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_sprinkler_percent <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_drip_percent <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_Irrigated_area

water_use_file$next_yr_sprinkler_rel <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_irrigated_area_gravity
water_use_file$next_yr_drip_rel <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_irrigated_area_gravity


read_data_1 <- merge(read_data_1, water_use_file, by='State')

read_data_1[,col_names] = log(read_data_1[, col_names])

write.csv(read_data_1, paste0(save_folder, 'R_openness.csv'))

column_names <- c('State', 'Real_Openness', 'Water_Use', 
                  'Constructed_Openness', 'Income',
                'Precipitation', 'Temperature', 'Population', 
                'Area', 'Latitude', 'Longitude', 'Income2', 'Is.DC')

column_names <- c(column_names, col_names)

lm_stage_1_1 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude, 
                 data = read_data_1)
summary(lm_stage_1_1)
nobs(lm_stage_1_1)

lm_stage_1_2 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_2)
nobs(lm_stage_1_2)

lm_stage_1_3 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_3)
nobs(lm_stage_1_3)

lm_stage_1_4 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_4)
nobs(lm_stage_1_4)

lm_stage_1_5 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent, 
                 data = read_data_1)
summary(lm_stage_1_5)
nobs(lm_stage_1_5)

####################
#################


lm_stage_2_1 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#### real to


lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#################

################# GW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

################## SW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


######################




lm_stage_2_1 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)


#### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################

##################

```

3. Year 2022

\textbf{Code} 
```{r}

library(MASS)
library(dplyr)

save_folder = '.\\Analysis_2022\\'


read_data_og <- read.csv(paste(save_folder,'instrument_training.csv',
                            sep=""))

# Assume your dataframe is called df
read_data <- read_data_og
#read_data <- read_data_og %>%
#  group_by(Exporter, Importer, SCTG) %>%
#  summarise(
#    Shipments = sum(Shipments),
#    across(-Shipments, ~ first(.)),  # keep first of other columns
#    .groups = "drop"
#  )

d <- data.frame(as.list(1:nrow(read_data)))
idx_d <- which(d%%2==1)
idx_no_self <- which(read_data[, 1]!=read_data[, 2])

subset_data<- read_data[intersect(idx_d, idx_no_self), ]
#subset_data<- read_data[idx_no_self, ]

self_just_once <- intersect(which(d%%2==1), which(read_data[, 1]==read_data[, 2]))
subset_data_2 <- read_data[self_just_once,]

subset_data_3 <- rbind(subset_data, subset_data_2)
#subset_data_3 <- subset_data
idx_not_CONUS <- which(subset_data_3[,1]==2 | subset_data_3[,1]==15 |
                         subset_data_3[,2]==2 | subset_data_3[,2]==15)
subset_data_3<-subset_data_3[-idx_not_CONUS, ]

subset_data_3 <- subset_data_3 %>%
  group_by(Exporter, Importer) %>%
  summarise(
    Shipments = sum(Shipments),
    across(-Shipments, ~ first(.)),  # keep first of other columns
    .groups = "drop"
  )

column_names<- c('Exporter', 'Importer', 'Shipments', 'Distance', 
                 'Area_exporter', 'Area_importer', 
                 'Population_exporter', 'Population_importer', 
                 'GDP_exporter', 'GDP_importer', 
                 'Intrastate_or_not', 'Share_Border', 
                 'BorderxArea_exporter', 'BorderxArea_importer',
                 'BorderxPop_exporter', 'BorderxPop_importer', 
                 'BorderxDist', 'sum_LL',
                 'Borderxsum_LL', 'Long_ex', 'Lat_ex', 'Long_im', 
                 'Lat_im', 'Is_DC_involved', 'LL_ex', 'LL_im',
                 'num_FAF_ex', 'num_FAF_im', 'remoteness_ex', 'remoteness_im')



take_log_columns = c('Shipments', 'Distance', 
                     'Area_exporter', 'Area_importer', 
                     'Population_exporter', 'Population_importer', 
                     'GDP_exporter', 'GDP_importer',
                     'remoteness_ex', 'remoteness_im')

subset_data_3[,take_log_columns] <- log(subset_data_3[,take_log_columns])

subset_data_3$Interstate_or_not <- 1-subset_data_3$Intrastate_or_not

subset_data_3$num_FAF_involved <- subset_data_3$num_FAF_ex+subset_data_3$num_FAF_im


row.names(subset_data_3) <- NULL

subset_data_3$Is_importer_north_rel <- pmax(0,sign(subset_data_3$Lat_im-subset_data_3$Lat_ex))
subset_data_3$Is_importer_east_rel <- pmax(0,sign(subset_data_3$Long_im-subset_data_3$Long_ex))

subset_data_3$Share_Border[which(subset_data_3$Exporter==subset_data_3$Importer)]<-1

subset_data_3$inter_B <- subset_data_3$Share_Border*subset_data_3$Interstate_or_not
subset_data_3$inter_D <- subset_data_3$Distance*subset_data_3$Interstate_or_not

subset_data_3$inter_sum_LL <-subset_data_3$Interstate_or_not*subset_data_3$sum_LL
subset_data_3$inter_num_FAF_involved <-subset_data_3$Interstate_or_not*subset_data_3$num_FAF_involved

subset_data_3$inter_A_im <-subset_data_3$Interstate_or_not*subset_data_3$Area_importer
subset_data_3$inter_P_im <-subset_data_3$Interstate_or_not*subset_data_3$Population_importer

subset_data_3$inter_A_ex <-subset_data_3$Interstate_or_not*subset_data_3$Area_exporter
subset_data_3$inter_P_ex <-subset_data_3$Interstate_or_not*subset_data_3$Population_exporter

subset_data_3$inter_is_im_n <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_north_rel
subset_data_3$inter_is_im_e <-subset_data_3$Interstate_or_not*subset_data_3$Is_importer_east_rel


subset_data_3$inter_B_A_im <-subset_data_3$Interstate_or_not*subset_data_3$Area_importer*subset_data_3$Share_Border
subset_data_3$inter_B_P_im <-subset_data_3$Interstate_or_not*subset_data_3$Population_importer*subset_data_3$Share_Border

subset_data_3$inter_B_A_ex <-subset_data_3$Interstate_or_not*subset_data_3$Area_exporter*subset_data_3$Share_Border
subset_data_3$inter_B_P_ex <-subset_data_3$Interstate_or_not*subset_data_3$Population_exporter*subset_data_3$Share_Border

subset_data_3$inter_B_sum_LL <-subset_data_3$Interstate_or_not*subset_data_3$sum_LL*subset_data_3$Share_Border
subset_data_3$inter_B_num_FAF_involved <-subset_data_3$Interstate_or_not*subset_data_3$num_FAF_involved*subset_data_3$Share_Border

lm_instrument <- glmmPQL(Shipments~
                           Interstate_or_not+
                           inter_D+
                           Area_importer+
                           Population_importer+
                           sum_LL+
                           num_FAF_involved+
                           inter_is_im_n+inter_is_im_e+
                           inter_A_im+inter_P_im+
                           inter_sum_LL+inter_num_FAF_involved+
                           inter_B
                        ,data = subset_data_3, family = gaussian, random=~ 1 | SCTG)


lm_instrument$fitted.values <- predict(lm_instrument,data = subset_data_3)


summary(lm_instrument)

plot(subset_data_3$Shipments, lm_instrument$fitted.values,
     xlab="Real Shipment Weight (tons)", ylab="Predicted Shipment Weight (tons)")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_shipments.jpg"));
dev.off ();

read_data_1 <- read.csv(paste(save_folder,'IV_training.csv',
                              sep=""))

idx_interstate <- which(subset_data_3[,1]!=subset_data_3[,2])

for(i in 1:nrow(read_data_1)){
  idx_state<-union(which(subset_data_3[,1]==read_data_1[i,1]),
                 which(subset_data_3[,2]==read_data_1[i,1]))
  
  #idx_state<-which(subset_data_3[,1]==read_data_1[i,1])
  
  idx_num <- intersect(idx_state, idx_interstate)
  #idx_num <- idx_state
  
  idx_den <- which(subset_data_3[,1]==read_data_1[i, 1])
  
  real_num <- sum(exp(subset_data_3$Shipments[idx_num]), na.rm=TRUE)
  temp_num <- sum(floor(exp(lm_instrument$fitted.values[idx_num])), na.rm=TRUE)
  
  #temp_num <- sum(exp(lm_instrument$fitted.values[idx_num]), na.rm=TRUE)
  
  real_den <- sum(exp(subset_data_3$Shipments[idx_den]), na.rm=TRUE)
  temp_den <- sum(floor(exp(lm_instrument$fitted.values[idx_den])), na.rm=TRUE)
  
  read_data_1$Real_Openness[i] <- real_num/real_den
  read_data_1$Constructed_Openness[i] <- temp_num/real_den
  #read_data_1$Real_Openness[i] <- real_num
  #read_data_1$Constructed_Openness[i] <- temp_num
}

plot(read_data_1$Real_Openness, read_data_1$Constructed_Openness,
     xlab="Real Trade Openness", ylab = "Constructed Trade Openness")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_trade_og.jpg"));
dev.off ();

read_data_1$Real_Openness <- log10(read_data_1$Real_Openness+1)
read_data_1$Constructed_Openness <- log10(read_data_1$Constructed_Openness+1)

plot(read_data_1$Real_Openness, read_data_1$Constructed_Openness,
     xlab="Real Trade Openness", ylab = "Constructed Trade Openness")
abline(0, 1, col = "red", lwd = 2)  # Intercept = 0, slope = 1
dev.copy(jpeg,filename=paste0(save_folder,"R_observed_simulated_trade.jpg"));
dev.off ();

read_data_1_next_yr <- read.csv(paste(save_folder,'IV_training_next_yr.csv',
                              sep=""))

read_data_1 <- merge(read_data_1, read_data_1_next_yr, by='State')

water_use_file <- read.csv(paste(save_folder,'water_data_states.csv',
                                 sep=""))
col_names <- c('same_yr_Irrigated_area',	'next_yr_Irrigated_area',
               'next_yr_Irrigated_area_gw', 'next_yr_Irrigated_area_sw',
               'next_yr_Irrigated_water',	'next_yr_Irrigated_water_gw',	
               'next_yr_Irrigated_water_sw',	'next_yr_irrigated_area_gravity',
              'next_yr_irrigated_area_sprinkler',	'next_yr_irrigated_area_drip')

water_use_file$next_yr_gravity_percent <- water_use_file$next_yr_irrigated_area_gravity/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_sprinkler_percent <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_Irrigated_area
water_use_file$next_yr_drip_percent <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_Irrigated_area

water_use_file$next_yr_sprinkler_rel <- water_use_file$next_yr_irrigated_area_sprinkler/water_use_file$next_yr_irrigated_area_gravity
water_use_file$next_yr_drip_rel <- water_use_file$next_yr_irrigated_area_drip/water_use_file$next_yr_irrigated_area_gravity


read_data_1 <- merge(read_data_1, water_use_file, by='State')

read_data_1[,col_names] = log(read_data_1[, col_names])

write.csv(read_data_1, paste0(save_folder, 'R_openness.csv'))

column_names <- c('State', 'Real_Openness', 'Water_Use', 
                  'Constructed_Openness', 'Income',
                'Precipitation', 'Temperature', 'Population', 
                'Area', 'Latitude', 'Longitude', 'Income2', 'Is.DC')

column_names <- c(column_names, col_names)

read_data_1 <- read_data_1[is.finite(rowSums(read_data_1)),]

lm_stage_1_1 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude, 
                 data = read_data_1)
summary(lm_stage_1_1)
nobs(lm_stage_1_1)

lm_stage_1_2 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_2)
nobs(lm_stage_1_2)

lm_stage_1_3 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_3)
nobs(lm_stage_1_3)

lm_stage_1_4 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr, 
                 data = read_data_1)
summary(lm_stage_1_4)
nobs(lm_stage_1_4)

lm_stage_1_5 <- lm(Real_Openness ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent, 
                 data = read_data_1)
summary(lm_stage_1_5)
nobs(lm_stage_1_5)

####################
#################


lm_stage_2_1 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#### real to


lm_stage_2_4 <- lm(next_yr_Irrigated_area ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


#################

################# GW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

################## SW

lm_stage_2_1 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)



#### real to next yr

lm_stage_2_4 <- lm(next_yr_Irrigated_area_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)


######################




lm_stage_2_1 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)


#### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_gw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

################


lm_stage_2_1 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude,
                 data = read_data_1)
summary(lm_stage_2_1)
nobs(lm_stage_2_1)

lm_stage_2_2 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr,
                 data = read_data_1)
summary(lm_stage_2_2)
nobs(lm_stage_2_2)

lm_stage_2_3 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_3)
nobs(lm_stage_2_3)

lm_stage_2_4 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr,
                 data = read_data_1)
summary(lm_stage_2_4)
nobs(lm_stage_2_4)

lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Constructed_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

### real to
lm_stage_2_5 <- lm(next_yr_Irrigated_water_sw ~ Real_Openness+Population_next_yr+Area+
                     Latitude+Longitude+Precipitation_next_yr+Temperature_next_yr+
                     Income_next_yr+Tot_Employment_next_yr+Agri_Employment_next_yr
                     +next_yr_gravity_percent+next_yr_sprinkler_percent+next_yr_drip_percent,
                 data = read_data_1)
summary(lm_stage_2_5)
nobs(lm_stage_2_5)

##################

```